import AbstractApp from '@/components/app/AbstractApp'
import { Inter } from 'next/font/google'
import { globalStyles } from '@/styles'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Link in Bio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  globalStyles();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AbstractApp>
          {children}
        </AbstractApp>
      </body>
    </html>
  )
}
